{% set name = "sheet2dict" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sheet2dict-{{ version }}.tar.gz
  sha256: efa356159dedc05a57482b50dd01fe870d8b4ae589ec97253701e526fda3f269

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - openpyxl
    - python >={{ python_min }}

test:
  imports:
    - sheet2dict
    - tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Pytlicek/sheet2dict
  summary: Simple XLSX and CSV to dictionary converter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
